Added basic functionality to UI
andrew-fennell/CogNative pull request #79
Opened 2022-04-18 04:45 UTC by andrew-fennell

## Summary
Added functionality to the "Clone voice" button. It now runs ```python -m CogNative.main``` with all arguments given.

The final line of the output will be printed to the GUI. This is typically "ERROR: <some error>" or "Cloned output to <some location>". It will either print in red or green, depending on if it is an "ERROR".

The way I have done everything in this branch is NOT the best way to do it. I am trying to get the UI to a workable place so it can be improved upon.

## Examples
### Success case
![image](https://user-images.githubusercontent.com/28690153/163755788-e5d65127-ccdb-4783-a7ae-d9962c54875b.png)

### Error Case
![image](https://user-images.githubusercontent.com/28690153/163755711-78ec92e5-50db-4191-93a0-7702c849f1d8.png)

All inputs on the UI should be functional. I removed any that would no longer be used (with language auto-detection added in #78 and #71)

Closes #76

2022-04-19 22:39 UTC, JacobSmith1020 requested changes
Suggestions: Might want to show what folders the user selected for the various audio inputs in the UI. We also might want to make it more clear what fields are required and what fields are mutually exclusive with one another. Should also add to the readme the commands to start the UI and main; that is ```python -m CogNative.testUI.UI``` and ```python -m CogNative.main```. At some point we might want to allow an option to enter a txt file as input instead of exclusively having the user manually type in the text box.

Issues: The use saved embedding checkbox does not do anything (the command line argument being passed here is hardcoded as 'y'). When you clone a voice and it outputs the filepath at the end in green once it's done, if you click clone voice again it will not get rid of the green filepath and instead will print the "Cloning Voice..." text on top of it.

2022-04-19 22:39 UTC, JacobSmith1020 commented on CogNative/testUI/UI.py
> +           '-useExistingEmbed', 'y'
This should be connected to the corresponding check box.

2022-04-19 22:43 UTC, andrew-fennell commented on CogNative/testUI/UI.py
> +           '-useExistingEmbed', 'y'
```suggestion
           '-useExistingEmbed', data["input"]["use_embedding"]
```

This should fix the issue.

2022-04-19 22:49 UTC, andrew-fennell commented
> Might want to show what folders the user selected for the various audio inputs in the UI.

I agree! I'll add this.

> Should also add to the readme the commands to start the UI and main

This should have been introduced with #84. I will merge main into this branch.

> At some point we might want to allow an option to enter a txt file as input instead of exclusively having the user manually type in the text box.

I just opened another issue to address this. I think it is a good idea. #86

2022-04-20 17:04 UTC, andrew-fennell commented
The biggest error in this is that when the GUI exits, the process finishes running. 

I think this is a significant problem, but it is going to take some effort to fix it.

2022-04-20 17:07 UTC, andrew-fennell commented
Updated example with a **.txt** file selected as user input.
![image](https://user-images.githubusercontent.com/28690153/164285016-b8070764-4abc-4080-aae4-884550bea853.png)

If the text file or "audio to transcribe" file is too long, it will print 80 characters followed by "...".

2022-04-20 19:24 UTC, JacobSmith1020 approved these changes
We probably don't want to leave the file extension for the output up to the user, should just ask for a name and export as a wav by default. Not a big deal if left the way it is though.

There is also still the small visual issue where the green output at the bottom will be overwritten by successive requests to clone a voice and by error messages that may pop up:

![image](https://user-images.githubusercontent.com/74121635/164307001-e70488c4-4c08-4669-a2c8-b90b8b0d3b54.png)

![image](https://user-images.githubusercontent.com/74121635/164307143-eb8b473d-fdda-4643-a32b-357519bbcd73.png)

Other than that, this looks great :)

2022-04-20 20:03 UTC, andrew-fennell commented
> There is also still the small visual issue where the green output at the bottom will be overwritten by successive requests to clone a voice and by error messages that may pop up:

Due to the demo timeline closing in, I'll merge this and open issues regarding the other smaller issues. These can be fixed in smaller PRs. This isn't best practice, but this tool will be helpful in quickly generating demo audio.

#89 
#90

2022-04-20 20:03 UTC, merged