Script for splitting audio files by silences
andrew-fennell/CogNative pull request #83
Opened 2022-04-18 20:14 UTC by tisArc98

2022-04-19 22:54 UTC, JacobSmith1020 submitted a review, later dismissed
Needs some minor changes to be compatible with the current project but it's fine for now as a standalone file.

2022-04-19 22:54 UTC, JacobSmith1020 commented on CogNative/backend/modules/audio_split.py
> +assert file_check, print(f"{Fore.YELLOW}Please move audio file to 'Clone_Tests/Raw/'")
Might want to change extension to wav and adjust the filepath for future integration.

2022-04-20 00:11 UTC, andrew-fennell commented
## Summary of changes made

The script will **ensure** that EVERY chunk is under 45 seconds long (good to send to Google's API).

I added a "optimize" option, but it is really just there to try to encourage the chunks to be closer to 45 seconds. The flow is _might_ be better when optimize is used, but we will need to test it to see.

## Time taken to split
### TCOC40.wav
Initial script: 02:34

New version, unoptimized slices: 02:32

New version, optimized slices:  06:01

### Angelina.wav
Initial  script: 00:32

New version, unoptimized slices: 00:39

New version, optimized slices: 01:27

2022-04-20 13:15 UTC, andrew-fennell commented
## Tests to run on this branch

```python -m CogNative.main```

```python -m CogNative.audio_split```

```python -m CogNative.STT```

2022-04-20 20:23 UTC, JacobSmith1020 requested changes
@andrew-fennell Walked through CogNative.main, CogNative.backend.modules.STT, and CogNative.backend.modules.audio_split. All working for small file inputs but I ran through main with the TCOC40 for audio transcription and ran into an issue after the transcription was done. It looks like some segment of the translator threw an error for a large transcription.

![image](https://user-images.githubusercontent.com/74121635/164316104-a88bccbf-3210-4bd2-b44a-c6df6ec31240.png)

2022-04-20 20:28 UTC, JacobSmith1020 approved these changes
The audio splitting is working great :)

2022-04-20 20:32 UTC, merged

2022-04-21 03:41 UTC, andrew-fennell commented
This PR has fixed this issue mentioned in #87 due to the audio splitting.